### ISSUE TITLE
ruby 2.3?

### ISSUE THREAD

**Issue by lifeiscontent** [lgromanowski/letsencrypt-plugin#24] opened 2016-02-11 07:40 UTC
Any reason why this can't run on ruby 2.3?

**Comment by lgromanowski** [comment] 2016-02-12 17:20
Hi,
it should work with ruby 2.3. In gemspec file there is requirement for minimal ruby version - letsencrypt_plugin  won't work on ruby older than 2.1.0 (because of acme-client, which requires ruby v2.1.0).

**Comment by lifeiscontent** [comment] 2016-02-12 21:04
@lgromanowski I keep getting errors when the plugin mounts. If you're willing to help debug I can post the logs.

**Comment by lgromanowski** [comment] 2016-02-13 20:01
Yes, please post logs I'll try to figure out why it's not working with v2.3

**Comment by pmn** [comment] 2016-02-27 22:05
I'm getting this error. Here are the logs: 

```
Installing letsencrypt_plugin 0.0.7

Gem::InstallError: letsencrypt_plugin requires Ruby version ~> 2.1.0.
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:601:in `ensure_required_ruby_version_met'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:817:in `pre_install_checks'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:272:in `install'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:142:in `block in install'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:151:in `preserve_paths'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:134:in `install'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/installer/gem_installer.rb:56:in `install'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/installer/gem_installer.rb:14:in `install_from_spec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/installer/parallel_installer.rb:90:in `block in worker_pool'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/worker.rb:55:in `apply_func'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/worker.rb:50:in `block in process_queue'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47:in `loop'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47:in `process_queue'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/worker.rb:22:in `block (2 levels) in initialize'
An error occurred while installing letsencrypt_plugin (0.0.7), and Bundler
cannot continue.
Make sure that `gem install letsencrypt_plugin -v '0.0.7'` succeeds before
bundling.
```

Here's the output of `ruby --version`:
```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

**Comment by halo** [comment] 2016-03-03 12:28
This is already [fixed in master](https://github.com/lgromanowski/letsencrypt-plugin/commit/84bd9088cfe04672734364a3147977b3976cc7a4) but has not made it to rubygems yet. See also [this discussion](https://github.com/lgromanowski/letsencrypt-plugin/commit/bfca05f28924e20113f95b4a50d0b4e99de0067d#commitcomment-15646161)

**Comment by iaybar** [comment] 2016-03-07 20:00
When I ran bundle install in my ruby 2.2.2 project , I get this >

```
Installing letsencrypt_plugin 0.0.7

Gem::InstallError: letsencrypt_plugin requires Ruby version ~> 2.1.0.
An error occurred while installing letsencrypt_plugin (0.0.7), and Bundler cannot continue.
Make sure that `gem install letsencrypt_plugin -v '0.0.7'` succeeds before bundling.

```

Here is my rvm list result >

```
rvm rubies

   ruby-2.1.0 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.1.7 [ x86_64 ]
   ruby-2.1.8 [ x86_64 ]
=* ruby-2.2.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

```

Any help?

**Comment by halo** [comment] 2016-03-07 20:21
@iaybar Use an older version of the gem for now:

```ruby
gem 'letsencrypt_plugin', '0.0.6'
```

and wait until @lgromanowski releases `0.0.8` [on Rubygems](https://rubygems.org/gems/letsencrypt_plugin/versions).

As I mentioned earlier, the problem is already fixed in the code, it has not been packaged and distributed yet so you can take advantage of the newest code.

**Comment by bronson** [comment] 2016-03-28 20:46
Since 0.0.8 is released, is this issue solved?

**Comment by pedantic-git** [comment] 2016-03-28 20:49
Confirmed installable in my env.

**Comment by lgromanowski** [comment] 2016-03-30 15:43
Hi,
thanks for confirmation :) I'm closing this issue.

**Closed by lgromanowski** 2016-03-30 15:43 UTC
